### ISSUE TITLE
TypeError: basic_auth() got an unexpected keyword argument 'destiny'

### ISSUE THREAD

**Issue by Hugues862** [flask-extensions/Flask-SimpleLogin#38]
I have latest version and sometimes I see this message in my logs, no clue what it could be:

```
Traceback (most recent call last):
  File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/venv/lib/python3.8/site-packages/flask_simplelogin/__init__.py", line 333, in login
    return self.basic_auth(destiny=redirect(destiny))
TypeError: basic_auth() got an unexpected keyword argument 'destiny'
```

**Comment by cuducos** [comment]
Yep, this is a bug! Thanks for reporting. Probably I'll need to remove the `destiny=` from that line. But I need time to write proper tests for that. Cannot promise an ETA, but, once more, thanks for reporting : )
